# Generated by Django 5.0.6 on 2026-01-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='host',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='is_cover',
            new_name='is_primary',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('hotel', 'Hotel')], default='apartment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_guests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
